### ISSUE TITLE
Slash commands are timing out, prefix doesn't respond at all

### ISSUE THREAD

**Issue by GitWolf0** [dm94/lastoasisbot#22]
The bot is simply timing out. No commands are working on Discord.
![image](https://user-images.githubusercontent.com/22678541/157630122-e1651ba6-962a-457d-bd57-db2e7937e5ea.png)

**Comment by dm94** [comment]
Thanks for the report, after a permissions failure the bot has crashed.
This problem has been fixed in the latest version.
